name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build static frontend
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

      # Build and publish Python Function App
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r api/requirements.txt

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
          func azure functionapp publish ${{ secrets.FUNCTION_APP_NAME }} --python
